### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by rwilsond** [bossley9/website-minifier#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.10.5
**Thrown From**: [website-minifier](https://github.com/bossley9/website-minifier) package 1.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of null

```
At /Users/sysadmin/.atom/packages/website-minifier/lib/minifier.js:99

TypeError: Cannot read property 'length' of null
    at Object.module.exports.inlineCSS (/packages/website-minifier/lib/minifier.js:99:29)
    at Object.module.exports.minifyHTML (/packages/website-minifier/lib/minifier.js:185:16)
    at Object.module.exports.genFiles (/packages/website-minifier/lib/minifier.js:235:27)
    at Object.minify (/packages/website-minifier/lib/website-minifier.js:98:18)
    at HTMLElement.websiteMinifierMinify (/packages/website-minifier/lib/website-minifier.js:71:45)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:350017)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:348492)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:669184)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:676568)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -8:31.5.0 editor:indent (input.hidden-input)
     -8:30.9.0 core:paste (input.hidden-input)
  2x -8:30.2.0 core:save (input.hidden-input)
     -7:29.9.0 core:copy (input.hidden-input)
     -6:58.7.0 core:select-all (input.hidden-input)
     -6:58.4.0 core:copy (input.hidden-input)
     -6:49.1.0 core:select-all (input.hidden-input)
     -6:48.7.0 core:copy (input.hidden-input)
  2x -5:36.4.0 core:delete (input.hidden-input)
     -5:35.5.0 core:select-all (input.hidden-input)
     -5:35.2.0 core:copy (input.hidden-input)
     -4:56.9.0 core:save (input.hidden-input)
  4x -4:26.7.0 core:delete (input.hidden-input)
     -4:25.4.0 core:save (input.hidden-input)
  5x -1:22.8.0 tree-view:remove (span.name.icon.css3-icon.medium-blue)
     -0:15 website-minifier:minify (input.hidden-input)
```

### Non-Core Packages

```
atom-minify 0.8.0 
autocomplete-wordpress-hooks 0.2.3 
autoprefixer 3.7.1 
file-icons 2.1.28 
git-clone 0.2.0 
html-include-resource 1.3.0 
website-minifier 1.2.0 
wordpress-autocomplete 1.5.0 
```

**Comment by n8lauscher** [comment]
same-problem

**Comment by bossley9** [comment]
Apologies for the late reply. This issue has been fixed and published to Atom. Try updating the package.
